import 'package:rantal/model/userinfo_model.dart';
import 'package:rxdart/subjects.dart';
import 'package:rantal/service/repository.dart';
import 'package:rantal/service/firebsefetch.dart';
class userinfo_bloc {
  Repository _repository = Repository();

  final _dataFetch = PublishSubject<userinfo>();

  Stream<userinfo> get data => _dataFetch.stream;

  fetdata() async {
    userinfo autogenerated = _repository.fetchdata1();
    print(autogenerated);
    _dataFetch.sink.add(autogenerated);
  }

  depose() {
    _dataFetch.close();
  }
}
